[tool.commitizen]
version = "4.6.2"
update_changelog_on_bump = true
tag_format = "v$version"
changelog_start_rev = "v4.6.2"
changelog_merge_prerelease = true
annotated_tag = true
bump_message = "chore(update): Update version to $new_version"
version_files = [
    "esptool/__init__.py:__version__"
]