name: GitHub release

on:
  push:
    tags:
      - v*.*

jobs:
  create_release:
    name: Create GitHub release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
      VERSION: ${{ steps.get_version.outputs.VERSION }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Version ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Get version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
        shell: bash

  build-esptool-binaries:
    name: Build esptool binaries for ${{ matrix.os }}
    needs: create_release
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
        include:
        - os: macos-latest
          TARGET: macos
        - os: ubuntu-latest
          TARGET: linux-amd64
        - os: windows-latest
          TARGET: win64
    env:
      DISTPATH: esptool-${{ needs.create_release.outputs.VERSION }}-${{ matrix.TARGET }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v1

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: 3.8

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller
          pip install --user -e .

      - name: Build with PyInstaller
        run: |
          pyinstaller --distpath ./${{ env.DISTPATH }} -F --icon=.github/espressif.ico esptool.py
          pyinstaller --distpath ./${{ env.DISTPATH }} -F --icon=.github/espressif.ico espefuse.py
          pyinstaller --distpath ./${{ env.DISTPATH }} -F --icon=.github/espressif.ico espsecure.py
          pyinstaller --distpath ./${{ env.DISTPATH }} -F --icon=.github/espressif.ico esp_rfc2217_server.py

      # - name: Sign binaries
      #   if: matrix.os == 'windows-latest'
      #   env:
      #     CERTIFICATE: ${{ secrets.CERTIFICATE }}
      #     CERTIFICATE_PASSWORD: ${{ secrets.CERTIFICATE_PASSWORD }}
      #   shell: pwsh
      #   run: |
      #     ./.github/Sign-File.ps1 -Path ./${{ env.DISTPATH }}/esptool.exe
      #     ./.github/Sign-File.ps1 -Path ./${{ env.DISTPATH }}/espefuse.exe
      #     ./.github/Sign-File.ps1 -Path ./${{ env.DISTPATH }}/espsecure.exe
      #     ./.github/Sign-File.ps1 -Path ./${{ env.DISTPATH }}/esp_rfc2217_server.exe

      - name: Test and package (Linux/MacOS)
        if: matrix.os != 'windows-latest'
        run: |
          ./${{ env.DISTPATH }}/esptool -h
          ./${{ env.DISTPATH }}/espefuse -h
          ./${{ env.DISTPATH }}/espsecure -h
          ./${{ env.DISTPATH }}/esp_rfc2217_server -h
          mv LICENSE README.md ./${{ env.DISTPATH }}
          zip -r ${{ env.DISTPATH }}.zip ./${{ env.DISTPATH }}/*
      - name: Test and package (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: |
          ./${{ env.DISTPATH }}/esptool.exe -h
          ./${{ env.DISTPATH }}/espefuse.exe -h
          ./${{ env.DISTPATH }}/espsecure.exe -h
          ./${{ env.DISTPATH }}/esp_rfc2217_server.exe -h
          mv LICENSE README.md ./${{ env.DISTPATH }}
          7z a ${{ env.DISTPATH }}.zip ./${{ env.DISTPATH }}

      - name: Upload release assets
        id: upload-release-asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: "${{ env.DISTPATH }}.zip"
          asset_name: "${{ env.DISTPATH }}.zip"
          asset_content_type: application/zip

